config/routes.rb
Rails.application.routes.draw do
  resources :organizations

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/organization.rb
class Organization < ActiveRecord::Base
	

	def politics
		[personal, economic, political].inject(:+)
	end
	def is_guarded
		return DateTime.now < guarded_until
	end
	def manipulate
		return Random.rand(1..fight) - modifiers
	end
	def manipulated!
		manipulated_until = DateTime.now + 0
	end
	def is_manipulated
		# return DateTime.now < guarded_until
	end

	# Organizational Combat
	# =====================
	def modifiers
		m = 0
		m += 2 if is_manipulated
		m += wounds
	end
	def attack
		return Random.rand(1..fight) - modifiers
	end
	def parry
		(2 + 0.5 * fight).to_i - modifiers
	end
	def toughness
		(2 + 0.5 * vigor).to_i - modifiers
	end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :slogan, :control, :wealth, :income, :power, :inflluence, :morale, :security, :orthodoxy, :violence, :slant, :authority, :sector, :criminality, :zeal, :strangeness)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
	def show_alignments(o)
		 [
			kratos(o.kratos),
		
		    reverence(o.reverence),
		
			sector(o.sector),
		
			law(o.law),
			zeal(o.zeal),
			odd(o.odd),
			show_politics(o)
		 ].compact.join(", ").html_safe
	end
	def show_politics(o)
		nolan = case 
			when (o.personal > 1 and o.economic > 1) then "Libertarian"
			when (o.personal < -1 and o.economic < -1) then "Statist"
			when (o.personal > 1 and o.economic < -1) then "Leftist"
			when (o.personal < -1 and o.economic > 1) then "Rightist"
			else "Centrist"
		end
		jennifer = if o.political > 1 
			"Permissive"
		elsif o.political < -1
			"Repressed"
		else
			nil
		end
		return [jennifer, nolan].compact.join(" ")

	end
	def kratos(i,j=0)
		level = {
			'3' => 'Violent',
			'2' => 'Violent',
			'1' => nil,
			'0' => nil,
			'-1' => nil,
			'-2' => 'Peaceful',
			'-3' => 'Peaceful',
		}[i.to_s]
		level += " (#{i})" if (j == 1)
		level
	end
	def zeal(i,j=0)
		level = {
			'3' => 'Zealous',
			'2' => 'Zealous',
			'1' => nil,
			'0' => nil,
			'-1' => nil,
			'-2' => 'Apathetic',
			'-3' => 'Apathetic',
		}[i.to_s]
		level += " (#{i})" if (j == 1)
		level
	end
	def law(i,j=0)
		level = {
			'3' => 'Lawful',
			'2' => 'Lawful',
			'1' => nil,
			'0' => nil,
			'-1' => nil,
			'-2' => 'Criminal',
			'-3' => 'Criminal',
		}[i.to_s]
		level += " (#{i})" if (j == 1)
		level
	end
	def odd(i,j=0)
		level = {
			'3' => 'Strange',
			'2' => 'Odd',
			'1' => nil,
			'0' => nil,
			'-1' => nil,
			'-2' => 'Normal',
			'-3' => 'Boring',
		}[i.to_s]
		level += " (#{i})" if (j == 1)
		level
	end
	def reverence(i,j=0)
		level = {
			'3' => 'Theist',
			'2' => 'Theist',
			'1' => nil,
			'0' => nil,
			'-1' => nil,
			'-2' => 'Atheist',
			'-3' => 'Atheist',
		}[i.to_s]
		level += " (#{i})" if (j == 1)
		level
	end
	def degrees(low,hi,value)
		adj = %w(Totally Very Slightly Not Slightly Very Totally)[value + 3]
		adj = 'Far' if low == 'Left' and value.abs == 3
		return "#{adj} #{low}" if value < 0
		return "#{adj} #{hi}"
	end
	def excrement(left, right, value)
		return degrees(left,right,value)
		percent = ((value.to_f + 4.to_f) / 0.07).to_i - 7
		row = <<-EOS;
		<div class='row'>
		  <div class='medium-2 large-2 columns'>#{left}</div>
		  <div class='medium-7 large-7 columns progress'><span class='meter' style='width:#{percent}%'></span></div>
		  <div class='medium-2 large-2 columns'>#{right}</div>
		</div>
		EOS
		row.html_safe
	end
	def starTrait(l,r,i,j=0)
		x = i + 3
		cells = ["<th>#{l}</th>"]
		7.times do |j|
			cells << if j == x
				"<td>*</td>"
			else
				"<td></td>"
			end
		end
		cells << "<th>#{r}</th>"
		return "<tr>#{cells.join("\n")}</tr>".html_safe
	end
	def ptraits(i,j=0)
		traits(i-3,j)
	end
	def traits(i,j=0)
		level = {'3' => 'Superb',
		'2' => 'Great',
		'1' => 'Good',
		'0' => 'Fair',
		'-1' => 'Mediocre',
		'-2' => 'Poor',
		'-3' => 'Terrible',
		}[i.to_s]
		level += " (#{i})" if (j == 1)
		level
	end
	def sector(i,j=0)
		level = {
			'3' => 'Private',
			'2' => 'Private',
			'1' => 'Private',
			'0' => 'Non-Profit',
			'-1' => 'Public',
			'-2' => 'Public',
			'-3' => 'Public',
		}[i.to_s]
		level += " (#{i})" if (j == 1)
		level
	end
end

app/views/organizations/_form.html.haml
= simple_form_for(@organization) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :slogan
    = f.input :control
    = f.input :wealth
    = f.input :income
    = f.input :power
    = f.input :inflluence
    = f.input :morale
    = f.input :security
    = f.input :orthodoxy
    = f.input :violence
    = f.input :slant
    = f.input :authority
    = f.input :sector
    = f.input :criminality
    = f.input :zeal
    = f.input :strangeness

  .form-actions
    = f.button :submit

app/views/organizations/_organization.html.haml
%div.row
  %h3= link_to organization.name, organization
  %div.row
    %div.small-9.columns
      %strong Slogan:
      = organization.slogan
  %div.row
    %div.small-4.columns
      %div.row
        %div.small-4.columns
          %strong 
            %abbr{:title => "Power & Influence"}P/I:
        %div.small-8.columns.end
          = ptraits(organization.strength)
          \/
          = ptraits(organization.agility)
      %div.row
        %div.small-4.columns
          %strong Morale:
        %div.small-8.columns.end
          = ptraits(organization.vigor)
      %div.row
        %div.small-4.columns
          %strong Resist:
        %div.small-8.columns.end
          = ptraits(organization.toughness)
      %div.row
        %div.small-4.columns
          %strong Notice:
        %div.small-8.columns.end
          = ptraits(organization.notice)
    %div.small-8.columns.dev
      = show_alignments(organization)

app/views/organizations/edit.html.haml
%h1 Editing organization

= render 'form'

= link_to 'Show', @organization
\|
= link_to 'Back', organizations_path

app/views/organizations/index.html.haml
= render :partial => @organizations

/ t.integer :strength  # Power
/ t.integer :notice    # Notice
/ t.integer :vigor     # Morale
/ t.integer :toughness # Resistance
/ t.integer :agility   # Influence
/ t.integer :wounds    # Wounds

/ #
/ t.datetime :manipulated_until
/ t.datetime :guarded_until

/ t.integer :cp
/ # Personnel 
/ t.integer :leaders
/ t.integer :cadre
/ t.integer :recruits
/ # How visible a group's data is.
/ t.integer :secrecy
/ # Cash
/ t.integer :wealth
/ t.integer :income
/ # Type - for STI
/ t.string  :type 

/ # Alignments (Fudge, Applied to Attacks somehow)
/ # Violence - Violent (Kratos) / Peaceful (Akrateia) - Tendency to use force, violence
/ t.integer :kratos
/ # Religious - Atheist / Theist
/ t.integer :reverence
/ # Sector - Public / Charity / Private
/ t.integer :sector
/ # Law & Order - Criminal / Lawful
/ t.integer :law
/ # Zealous - Apathy / Zeal
/ t.integer :zeal
/ # Strangeness - Normal / Odd / Strange
/ t.integer :odd
/ # Politics
/ # t.integer :politics # Sum of each of the following for simple math.
/ # Personal Freedom - Archy / Anarchy - Rank recognition (equal v. rank)
/ t.integer :personal
/ # Economic Freedom - Socialist / Capitalist
/ t.integer :economic
/ # Political Freeom - Authoritarian / Libertarian
/ t.integer :political

app/views/organizations/new.html.haml
%h1 New organization

= render 'form'

= link_to 'Back', organizations_path

app/views/organizations/show.html.haml
%p#notice= notice

%h1
  Organization:
  = @organization.name

%p
  %b Slogan:
  = @organization.slogan

%p= show_alignments(@organization)

%div.row
  %div.small-8.columns
    %table{:width => '100%'}
      %tr
        %th Power
        %td= "#{@organization.strength}"
        %th{:colspan=>2} Points
        %td= @organization.cp
      %tr
        %th Income
        %td= @organization.income + 3
        %td= link_to "Inc.", "#"
        %td= link_to "Dec.", "#"
      %tr
        %th Wealth
        %td= @organization.wealth
        %td= link_to "Inc.", "#"
        %td= link_to "Dec.", "#"
      %tr
        %th &nbsp;
        %th -3
        %th -2
        %th -1
        %th 0
        %th 1
        %th 2
        %th 3
        %th &nbsp;
      = starTrait(reverence(-3),reverence(3),@organization.reverence)
      = starTrait(kratos(-3),kratos(3),@organization.kratos)
      = starTrait(sector(-3),sector(3),@organization.sector)
      = starTrait(law(-3),law(3),@organization.law)
      = starTrait(zeal(-3),zeal(3),@organization.zeal)
      = starTrait(odd(-3),odd(3),@organization.odd)

= link_to 'Edit', edit_organization_path(@organization)
\|
= link_to 'Back', organizations_path